import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@mui/material";
import UploadFileIcon from "@mui/icons-material/UploadFile";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button
          component="label"
          variant="outlined"
          startIcon={<UploadFileIcon />}
          sx={{ marginRight: "1rem" }}
        >
          Upload Sticker
          <input
            type="file"
            accept=".csv"
            hidden
            onChange={async () => {
              const response = await fetch("http://127.0.0.1:5000", {
                method: "POST",
              });
            }}
          />
        </Button>
      </main>
    </>
  );
}
